server:
  port: 60226
spring:
  datasource:
    url: jdbc:mysql://118.114.244.93:13306/zxwz_dev?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
      # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: xyz.fusheng.entity